before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags: -trimpath
    ldflags: -s -w
archives:
  - format: zip
release:
  github:
    owner: anugram
    name: terraform-provider-ciphertrust